{
    "application":      "FloodWorkshop Publisher",
    "copyright":        "&copy; Vightel, 2013",
    "contact":          "Pat Cappelaere",
    "contact_mail":     "pat@cappelaere.com",
    "HOSTBASEURL":      "http://ojo-bot.herokuapp.com",
    "PORT":				80,
    "worldmapid":       "cappelaere.map-1d8e1acq",
    "send_email": 		0,
    "regions" : {
        "Global": {
            "bbox":     [-170, 50, 170, -50 ],
            "target":   [-80, 20],
            "min_zoom":  2,
            "max_zoom":  12,
            "map_id":   "cappelaere.map-mx5g2tn3",
            "bucket":   "ojo-global",
            "ojotiler": "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888"
        },
        "d02": {
            "name":		"Central America",
            "bbox":     [-92.68, 6.17, -75.85, 19.08 ],
            "target":   [-84.14, 9.84],
            "min_zoom":  1,
            "max_zoom":  18,
            "map_id":   "cappelaere.map-mx5g2tn3",
            "bucket":   "ojo-d2",
            "ojotiler": "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888"
        },
        "d03": {
            "name":		"Hispaniola",
            "bbox":     [-74.94, 16.35, -64.98, 21.42 ],
            "target":   [-69.96, 18.89],
            "min_zoom": 6,
			      "max_zoom":	18,
            "map_id":   "cappelaere.map-q4hdwmh3",
            "bucket":   "ojo-d3",
            "ojotiler": "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888"
        },
        "d04": {
            "name":		"Namibia",
            "bbox":     [18, -21, 26, -17 ],
            "target":   [21.65,-18.12],
            "min_zoom": 6,
			      "max_zoom":	18,
            "map_id":   "cappelaere.map-q4hdwmh3",
            "bucket":   "rcmrd-products",
            "ojotiler": "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888"
        },
        "d05": {
            "name":		      "Malawi",
            "bbox":         [-74.94, 16.35, -64.98, 21.42 ],
            "target":       [-70.08, 20.22],
            "min_zoom":     7,
            "max_zoom":	    18,
            "map_id":       "cappelaere.map-q4hdwmh3",
            "bucket":       "rcmrd-products",
            "ojotiler":     "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888",
            "susmap":       "cappelaere.3uf4a15n"
        },
        "d06": {
            "name":		      "Pakistan",
            "bbox":         [60, 20, 80, 40 ],
            "target":       [70, 30],
            "min_zoom":     5,
            "max_zoom":	    18,
            "map_id":       "cappelaere.map-q4hdwmh3",
            "bucket":       "ojo-d6",
            "ojotiler":     "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888",
            "susmap":       "cappelaere.3uf4a15n"
        },
        "d07": {
            "name":           "Eafrica",
            "bbox":         [21.77, -12.27, 51.09, 23.95 ],
            "target":       [34.70, 2.59],
            "min_zoom":     7,
            "max_zoom":     18,
            "map_id":       "cappelaere.map-q4hdwmh3",
            "bucket":       "rcmrd-products",
            "ojotiler":     "http://ojo-tiler.herokuapp.com",
            "ojotiler-dev": "http://localhost:8888",
            "susmap":       "cappelaere.3uf4a15n"
        },
    },
	
    "admins":   		[ "pat@cappelaere.com", "cappelaere@gmail.com" ],
	"support_email": 	["dalia.b.kirschbaum@nasa.gov","pat@geobliki.com"],
	
	"github":	{
		"user":				"vightel",
		"floods":			"gfc",
		"landslides":		"glc"
	},
	
	"nodes": [
          {
          		"source": 		"dfo",
          		"href": 		"/opensearch",
          		"checked":  	true,
				"selected":   false
          },
          {
          		"source": 		"digiglobe",
          		"href": 		"/opensearch",
          		"checked":  	true,
              "selected":   false
          },
        	{
        		"source": 		"eo1_ali",
        		"href": 		"/opensearch",
        		"checked":  	true,
				"selected":   false
        	},
        	{
        		"source": 		"ef5",
        		"href": 		"/opensearch",
        		"checked":  	true,
				"selected":   false
        	},
			{
				"source": 		"gpm",
			  	"href": 		"/opensearch",
				"checked": 		false,
				"selected":   false
			  },
          	{
        		"source": 		"landscan",
        		"href": 		"/opensearch",
        		"checked":  	true,
				"selected":   true
        	},
          	{
        		"source": 		"l8",
        		"href": 		"/opensearch",
        		"checked":  	true,
				"selected":   false
        	},
			{
		  		"source": 		"modis",
				"href": 		"/opensearch",
				"checked":  	true,
				"selected":   false
			},
			{
				"source": 		"modis_lst",
				"href": 		"/opensearch",
				"checked":  	true,
				"selected":   false
			},
			{
				"source": 		"noaa",
				"href": 		"/opensearch",
				"checked": 		false,
				"selected":   false
			},            
        	{
        		"source": 		"radarsat2",
        		"href": 		"/opensearch",
        		"checked":  	true,
				"selected":   false
        	},
        	{
        		"source": 		"trmm",
        		"href": 		"/opensearch",
        		"checked":  	true,
            "selected":   false
        	},
			{
				"source": 		"usgs",
				"href": 		"/opensearch",
				"checked": 		false,
				"selected":   false
			},
			{
				"source": 		"viirs",
				"href": 		"/opensearch",
				"checked": 		false,
				"selected":   false
			},
			{
				"source": 		"chirps",
				"href": 		"/opensearch",
				"checked": 		false,
				"selected":   false
			},
            {
                "source":       "rcmrd",
                "href":         "/opensearch",
                "checked":      false,
                "selected":   false
            }
 	],
	"valid_modis_tiles":             [
    "000E010N",
    "000E020N",
    "000E030N",
    "000E040N",
    "000E050N",
    "000E060N",
    "000E070N",
    "010E030S",
    "010E020S",
    "010E010S",
    "010E000S",
    "010E010N",
    "010E020N",
    "010E030N",
    "010E040N",
    "010E050N",
    "010E060N",
    "010E070N",
    "010W010N",
    "010W020N",
    "010W030N",
    "010W040N",
    "010W050N",
    "010W060N",
    "020E030S",
    "020E020S",
    "020E010S",
    "020E000S",
    "020E010N",
    "020E020N",
    "020E030N",
    "020E040N",
    "020E050N",
    "020E060N",
    "020E070N",
    "020W010N",
    "020W020N",
    "020W030N",
    "020W070N",
    "030E020S",
    "030E010S",
    "030E000S",
    "030E010N",
    "030E020N",
    "030E030N",
    "030E040N",
    "030E050N",
    "030E060N",
    "030E070N",
    "030W070N",
    "040E020S",
    "040E010S",
    "040E010N",
    "040E020N",
    "040E030N",
    "040E040N",
    "040E050N",
    "040E060N",
    "040E070N",
    "040W000S",
    "040W010S",
    "050E020N",
    "050E030N",
    "050E040N",
    "050E050N",
    "050E060N",
    "050E070N",
    "050W000S",
    "050W010S",
    "050W020S",
    "060E030N",
    "060E040N",
    "060E050N",
    "060E060N",
    "060E070N",
    "060W030S",
    "060W020S",
    "060W010S",
    "060W000S",
    "060W010N",
    "060W050N",
    "060W060N",
    "070E010N",
    "070E020N",
    "070E030N",
    "070E040N",
    "070E050N",
    "070E060N",
    "070E070N",
    "070W050S",
    "070W040S",
    "070W030S",
    "070W020S",
    "070W010S",
    "070W000S",
    "070W010N",
    "070W020N",
    "070W050N",
    "070W060N",
    "070W070N",
    "080E010N",
    "080E020N",
    "080E030N",
    "080E040N",
    "080E050N",
    "080E060N",
    "080E070N",
    "080W050S",
    "080W040S",
    "080W030S",
    "080W020S",
    "080W010S",
    "080W000S",
    "080W010N",
    "080W020N",
    "080W030N",
    "080W040N",
    "080W050N",
    "080W060N",
    "080W070N",
    "090E010N",
    "090E020N",
    "090E030N",
    "090E040N",
    "090E050N",
    "090E060N",
    "090E070N",
    "090W000S",
    "090W010N",
    "090W020N",
    "090W030N",
    "090W040N",
    "090W050N",
    "090W060N",
    "090W070N",
    "100E000S",
    "100E010N",
    "100E020N",
    "100E030N",
    "100E040N",
    "100E050N",
    "100E060N",
    "100E070N",
    "100W020N",
    "100W030N",
    "100W040N",
    "100W050N",
    "100W060N",
    "100W070N",
    "110E030S",
    "110E020S",
    "110E000S",
    "110E010N",
    "110E020N",
    "110E030N",
    "110E040N",
    "110E050N",
    "110E060N",
    "110E070N",
    "110W020N",
    "110W030N",
    "110W040N",
    "110W050N",
    "110W060N",
    "110W070N",
    "120E030S",
    "120E020S",
    "120E010S",
    "120E000S",
    "120E010N",
    "120E020N",
    "120E030N",
    "120E040N",
    "120E050N",
    "120E060N",
    "120E070N",
    "120W030N",
    "120W040N",
    "120W050N",
    "120W060N",
    "120W070N",
    "130E030S",
    "130E020S",
    "130E010S",
    "130E000S",
    "130E040N",
    "130E050N",
    "130E060N",
    "130E070N",
    "130W040N",
    "130W050N",
    "130W060N",
    "130W070N",
    "140E040S",
    "140E030S",
    "140E020S",
    "140E010S",
    "140E000S",
    "140E040N",
    "140E050N",
    "140E060N",
    "140E070N",
    "140W060N",
    "140W070N",
    "150E030S",
    "150E020S",
    "150E060N",
    "150E070N",
    "150W070N",
    "160E040S",
    "160E060N",
    "160E070N",
    "160W020N",
    "160W030N",
    "160W060N",
    "160W070N",
    "170E040S",
    "170E030S",
    "170E070N",
    "170W060N",
    "170W070N",
    "180W070N"
    ]
}

